### ISSUE TITLE
Request matlab code or psychopy code for both sets of tasks, NTS task and MNAV task

### ISSUE THREAD

**Issue by hejuncuc** [jazlab/Neupane_Fiete_Jazayeri_mental_navigation#1]
Hello.
I'm interested in mental navigation tasks. Could you share matlab code or psychopy code for both sets of tasks, NTS task and MNAV task?
Thank you

**Comment by sujayane** [comment]
Hey @hejuncuc, we coded the task using custom software called mworks (https://mworks.github.io/). We didn't use Matlab or psychopy. If you are interested to try mworks, let me know and I will send you (or upload it here) a skeleton code with basic features of the task.

**Comment by sujayane** [comment]
Hey @hejuncuc, I have added the skeleton code under the 'utilities' folder to run mnav and NTS tasks in human subjects. You will need to install mworks to run them.
